version: '3'
services:
  web:
    build: .
    container_name: retrieval_pipeline
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0